[package]
name = "wasmtime-types"
version = "0.41.0"
authors = ["The Wasmtime Project Developers"]
description = "WebAssembly type definitions for Cranelift"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
documentation = "https://docs.rs/wasmtime-types"
edition = "2021"

[dependencies]
cranelift-entity = { path = "../../cranelift/entity", version = "0.88.0", features = ['enable-serde'] }
serde = { version = "1.0.94", features = ["derive"] }
thiserror = "1.0.4"
wasmparser = { git = "https://github.com/effect-handlers/wasm-tools", branch = "func-ref-2", default-features = false }
