(module
  (type $t1 (func))
  (type $c1 (cont $t1))
  (func $f1)
  (func $f2 (unreachable))
  (table $t 2 funcref)
  (elem (table $t) (i32.const 0) funcref (ref.func $f1))
  (elem (table $t) (i32.const 1) funcref (ref.func $f2))
  (func (export "main")
    (resume (cont.new (type $c1) (ref.func $f1)))
  )
  (func (export "traps")
    (resume (cont.new (type $c1) (ref.func $f2)))
  )
)

(invoke "main")
(assert_trap (invoke "traps") "unreachable")
